### ISSUE TITLE
哔哩哔哩漫画下载失败

### ISSUE THREAD

**Issue by SasakiKotoko** [lossme/ComicBook#41]
2020/12/15 12:21:00 onepiece.cli 178 [ERROR] download comicbook error. site=bilibili comicid=27866 chapter_number=6
Traceback (most recent call last):
  File "C:\Users\50256\AppData\Local\Programs\Python\Python39\lib\site-packages\onepiece-0.3.13-py3.9.egg\onepiece\cli.py", line 156, in download_main
    chapter = comicbook.Chapter(chapter_number, ext_name=ext_name)
  File "C:\Users\50256\AppData\Local\Programs\Python\Python39\lib\site-packages\onepiece-0.3.13-py3.9.egg\onepiece\comicbook.py", line 122, in Chapter
    chapter_item = self.crawler.get_chapter_item(citem)
  File "C:\Users\50256\AppData\Local\Programs\Python\Python39\lib\site-packages\onepiece-0.3.13-py3.9.egg\onepiece\site\bilibili.py", line 129, in get_chapter_item
    chapter_api_data = self.get_chapter_api_data(cid=citem.cid)
  File "C:\Users\50256\AppData\Local\Programs\Python\Python39\lib\site-packages\onepiece-0.3.13-py3.9.egg\onepiece\site\bilibili.py", line 81, in get_chapter_api_data
    raise ChapterNotFound(f"Please read on bilibili Manga APP. {source_url}")
onepiece.exceptions.ChapterNotFound: Please read on bilibili Manga APP. https://manga.bilibili.com/mc27866/436450

具体的也不知道什么错误好像是说章节找不到

是付费漫画不能下载吗，我看腾讯漫画付费的好像也能下载的样子

**Comment by lossme** [comment]
需要先购买，购买后才可以使用该工具的登录功能，把购买的漫画下载到本地

**Comment by lossme** [comment]
腾讯漫画要付费的话，那只能下载漫画的第一张图片
