### ISSUE TITLE
COCO漫画报错

### ISSUE THREAD

**Issue by fjjking** [lossme/ComicBook#48]
输入参数：
`python -m onepiece --site=cocomanhua --comicid=16601 --all`
报错：
`Traceback (most recent call last):
  File "D:\Program Files\ComicBook\onepiece\cli.py", line 170, in download_main
    chapter = comicbook.Chapter(chapter_number, ext_name=ext_name)
  File "D:\Program Files\ComicBook\onepiece\comicbook.py", line 143, in Chapter
    chapter_item = self.crawler.get_chapter_item(citem)
  File "D:\Program Files\ComicBook\onepiece\site\cocomanhua.py", line 73, in get_chapter_item
    image_urls = ctx.eval(f'getArr("{data}")')
  File "D:\Program Files\Python\lib\site-packages\pyexecjs-1.5.1-py3.9.egg\execjs\_abstract_runtime_context.py", line 27, in eval
    return self._eval(source)
  File "D:\Program Files\Python\lib\site-packages\pyexecjs-1.5.1-py3.9.egg\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "D:\Program Files\Python\lib\site-packages\pyexecjs-1.5.1-py3.9.egg\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "D:\Program Files\Python\lib\site-packages\pyexecjs-1.5.1-py3.9.egg\execjs\_external_runtime.py", line 87, in _exec_
    output = self._exec_with_pipe(source)
  File "D:\Program Files\Python\lib\site-packages\pyexecjs-1.5.1-py3.9.egg\execjs\_external_runtime.py", line 103, in _exec_with_pipe
    stdoutdata, stderrdata = p.communicate(input=input)
  File "D:\Program Files\Python\lib\subprocess.py", line 1130, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "D:\Program Files\Python\lib\subprocess.py", line 1498, in _communicate
    self._stdin_write(input)
  File "D:\Program Files\Python\lib\subprocess.py", line 1064, in _stdin_write
    self.stdin.write(input)
UnicodeEncodeError: 'gbk' codec can't encode character '\ufeff' in position 61: illegal multibyte sequence`

**Comment by lossme** [comment]
这个问题我这边未复现。
1. 更新代码后再试试
2. 检查网络是否正常，看下打开源站是否正常

**Comment by fjjking** [comment]
更新后仍然有问题，源网站打开正常。
感觉是编码问题（瞎猜），我暂时手动扒吧

**Comment by lossme** [comment]
可能是终端字符集的问题，配置下终端的字符集为UTF-8试试？

**Comment by fjjking** [comment]
依旧有这个问题终端改为utf-8还是同样的报错

**Comment by lossme** [comment]
https://github.com/lossme/ComicBook/issues/52
