### ISSUE TITLE
coco漫画报错

### ISSUE THREAD

**Issue by gulup** [lossme/ComicBook#51]
最新18版本，卸载后重装一样：
![image](https://user-images.githubusercontent.com/3413433/103842220-600fcd00-50d0-11eb-852e-671f877ead8c.png)
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\lib\site-packages\onepiece\__main__.py", line 4, in <module>
    main()
  File "C:\Python38\lib\site-packages\onepiece\cli.py", line 342, in main
    comicbook = ComicBook(site=site, comicid=comicid)
  File "C:\Python38\lib\site-packages\onepiece\comicbook.py", line 45, in __init__
    self.crawler = crawler_cls(comicid)
  File "C:\Python38\lib\site-packages\onepiece\crawlerbase.py", line 225, in __init__
    self.chekc_node_modules()
  File "C:\Python38\lib\site-packages\onepiece\crawlerbase.py", line 426, in chekc_node_modules
    raise RuntimeError(
RuntimeError: pleaese set node_modules directory and install crypto-js first. npm install crypto-js

**Comment by lossme** [comment]
1. 安装 node 环境
2. 安装 npm install crypto-js
3. 添加参数 `--node-modules ./node_modules` 重新下载
