### ISSUE TITLE
COCO漫画下载报错

### ISSUE THREAD

**Issue by gulup** [lossme/ComicBook#52]
最新版，1.8版本的
CMD页码设置了UTF-8一样报错
Active code page: 65001
2021/01/07 12:00:50 onepiece.worker 19 [INFO] set worker. worker=4
2021/01/07 12:00:51 onepiece.cli 273 [INFO] COCO漫画 【朋友游戏】 更新至: 085 【083 浪费时间】 数据来源: https://www.cocomanhua.com/15772
2021/01/07 12:00:52 onepiece.cli 186 [ERROR] download comicbook error. site=cocomanhua comicid=15772 chapter_number=1
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\onepiece\cli.py", line 163, in download_main
    chapter = comicbook.Chapter(chapter_number, ext_name=ext_name)
  File "C:\Python38\lib\site-packages\onepiece\comicbook.py", line 143, in Chapter
    chapter_item = self.crawler.get_chapter_item(citem)
  File "C:\Python38\lib\site-packages\onepiece\site\cocomanhua.py", line 63, in get_chapter_item
    js_content = open(self.COCOMANHUA_JS_PATH, encoding='utf-8').read()
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Python38\\lib\\site-packages\\onepiece\\js\\cocomanhua.js'
2021/01/07 12:00:53 onepiece.cli 186 [ERROR] download comicbook error. site=cocomanhua comicid=15772 chapter_number=2
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\onepiece\cli.py", line 163, in download_main
    chapter = comicbook.Chapter(chapter_number, ext_name=ext_name)
  File "C:\Python38\lib\site-packages\onepiece\comicbook.py", line 143, in Chapter
    chapter_item = self.crawler.get_chapter_item(citem)
  File "C:\Python38\lib\site-packages\onepiece\site\cocomanhua.py", line 63, in get_chapter_item
    js_content = open(self.COCOMANHUA_JS_PATH, encoding='utf-8').read()
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Python38\\lib\\site-packages\\onepiece\\js\\cocomanhua.js'
2021/01/07 12:00:54 onepiece.cli 186 [ERROR] download comicbook error. site=cocomanhua comicid=15772 chapter_number=3

![image](https://user-images.githubusercontent.com/3413433/103849704-627a2300-50e0-11eb-8b02-79a6aa4f28c4.png)

**Comment by lossme** [comment]
更新下代码试试

**Comment by gulup** [comment]
更新后报另外的错：
2021/01/07 14:22:20 onepiece.cli 186 [ERROR] download comicbook error. site=cocomanhua comicid=15772 chapter_number=16
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\onepiece\cli.py", line 163, in download_main
    chapter = comicbook.Chapter(chapter_number, ext_name=ext_name)
  File "C:\Python38\lib\site-packages\onepiece\comicbook.py", line 143, in Chapter
    chapter_item = self.crawler.get_chapter_item(citem)
  File "C:\Python38\lib\site-packages\onepiece\site\cocomanhua.py", line 65, in get_chapter_item
    image_urls = ctx.eval(f'getArr("{data}")')
  File "C:\Python38\lib\site-packages\execjs\_abstract_runtime_context.py", line 27, in eval
    return self._eval(source)
  File "C:\Python38\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "C:\Python38\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "C:\Python38\lib\site-packages\execjs\_external_runtime.py", line 87, in _exec_
    output = self._exec_with_pipe(source)
  File "C:\Python38\lib\site-packages\execjs\_external_runtime.py", line 103, in _exec_with_pipe
    stdoutdata, stderrdata = p.communicate(input=input)
  File "C:\Python38\lib\subprocess.py", line 1024, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Python38\lib\subprocess.py", line 1389, in _communicate
    self._stdin_write(input)
  File "C:\Python38\lib\subprocess.py", line 958, in _stdin_write
    self.stdin.write(input)
UnicodeEncodeError: 'gbk' codec can't encode character '\ufeff' in position 61: illegal multibyte sequence

**Comment by lossme** [comment]
这个编码报错的问题处理好了，但是coco漫画还是不能下载，站点的加密方法有改动，暂时搞不了

**Comment by lossme** [comment]
更新试下，好像是解决了
