### ISSUE TITLE
是否可以添加toomics的支持？

### ISSUE THREAD

**Issue by nqianaaron** [lossme/ComicBook#60]
您好，再次感謝大佬的項目。太好用了。自己購買的B站漫畫都能提取了。
另外我還購買了toomics的vip，不知道能否支持這個漫畫網站。

**Comment by lossme** [comment]
已经加上了，可以更新试下

**Comment by nqianaaron** [comment]
感謝大佬您的更新，我剛才也嘗試更新了下
然後使用命令：python -m pip install -U git+https://github.com/lossme/ComicBook。提示Successfully installed onepiece-0.3.22。這步驟應該沒有問題
但是參考您給的python -m onepiece --url "https://toomics.com/sc/webtoon/episode/toon/5062" -c 1。以及我自己參考help修改的命令python -m onepiece --site=toomics --comicid=5062 --all --cookies-path="C:\Users\hellsion\Desktop\ComicBook-master\toomics.json"。都無法下載（不帶cookie我也測試了，也不行。由於toomics很多都是收費的，應該是都要帶cookie的）
另外這兩種的錯誤提示還不同，具體如下，ps：下面兩種錯誤提示都只截取了部分錯誤信息。
我參考修改的錯誤提示：C:\Users\hellsion>python -m onepiece --site=toomics --comicid=5062 --all --cookies-path="C:\Users\hellsion\Desktop\ComicBook-master\toomics.json"
2021/01/24 12:01:41 onepiece.worker 19 [INFO] set worker. worker=4
2021/01/24 12:01:41 onepiece.cli 307 [INFO] load cookies success. C:\Users\hellsion\Desktop\ComicBook-master\toomics.json
Traceback (most recent call last):
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\site-packages\onepiece\__main__.py", line 4, in <module>
    main()
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\site-packages\onepiece\cli.py", line 422, in main
    comicbook.start_crawler()
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\site-packages\onepiece\comicbook.py", line 74, in start_crawler
    self.refresh()
您給的命令的錯誤提示：C:\Users\hellsion>python -m onepiece --url "https://toomics.com/sc/webtoon/episode/toon/5062" -c 1
2021/01/24 12:02:25 onepiece.worker 19 [INFO] set worker. worker=4
Traceback (most recent call last):
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 496, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

**Comment by lossme** [comment]
这个不清楚，重装python环境看下？

**Comment by nqianaaron** [comment]
您好，對於toomics是否支持登陸自己的vip賬號，下載R18或者收費的？現在好像衹能下載免費的。並且R18免費的都下不了。

**Comment by lossme** [comment]
好像是只有单话的漫画没有章节列表页面，会自动跳转到图片的页面

**Comment by lossme** [comment]
好像也不是 可以给下url吗

**Comment by lossme** [comment]
改了下，支持使用这样的url
```
python -m onepiece --url https://toomics.com/sc/webtoon/detail/code/103516/ep/1/toon/5131 --all
```

**Comment by lossme** [comment]
R18的内容需要使用cookies才能下载

**Comment by nqianaaron** [comment]
您好，換了台電腦，終於能下了。使用editthisCookie導出的cookie也能下載R18的了。但即使登陸的是vip賬號，還是不能下載後面的vip章節。不知道是不是不支持vip呢？

**Comment by lossme** [comment]
没vip账号，这个我测试不了

**Comment by nqianaaron** [comment]
我免费提供一个，我加您QQ，能通过一下么？

**Comment by lossme** [comment]
不用qq，要么加下群再私聊。或者发邮件也可以
https://t.me/onecomicbook
